### ISSUE TITLE
Write Tests for the API

### ISSUE THREAD

**Issue by LukvonStrom** [dsgnhb/api#19]
At the moment Testing is done completely with Postman. Some sort of unit tests would be a huge benefit for this project.

**Comment by MariliaMJ** [comment]
hies, I'd like to help writing tests. How can I join in?

**Comment by LukvonStrom** [comment]
@MariliaMJ  Fork the repo, choose a test runner write some tests and make a PR :)

**Comment by LukvonStrom** [comment]
And if you want to, you can integrate it in Gulp and Travis too :)

**Comment by gabrielsclimaco** [comment]
@MariliaMJ Are you currently working on this?

**Comment by LukvonStrom** [comment]
Is anyone working on this?
