### ISSUE TITLE
Better Integration of Gulp

### ISSUE THREAD

**Issue by LukvonStrom** [dsgnhb/api#22]
At the Moment Gulp is only used for building the API Docs. For the future it would be better to have some sort of watch/livereload setup and a integration for testing, which is  open in #19

**Comment by Jayflux** [comment]
should be able to pick this up

**Comment by FrancescoSaverioZuppichini** [comment]
Hello. I can help you. So let me see if I get this correct. You want:

- live reload of the server when you change the files
- integration for testing (probably mocha) and live reload when you change the tests

Correct? :)

**Comment by LukvonStrom** [comment]
@FrancescoSaverioZuppichini correct :)

**Comment by FrancescoSaverioZuppichini** [comment]
Perfect, I will work on this one :)
